### ISSUE TITLE
If MQTT settings are wrong, device will not reboot/save after configuration change

### ISSUE THREAD

**Issue by pfak** [revk/ESP32-Faikin#90] opened 2023-08-05 23:28 UTC
I entered wrong MQTT password, and no settings will save on the Web UI. It says "Settings saved", but they don't actually update the settings ..

**Comment by pfak** [comment] 2023-08-05 23:32
if I remove the MQTT information all together, then I get Rebooted and settings save

**Comment by pfak** [comment] 2023-08-05 23:34
nevermind that only worked once

**Comment by pfak** [comment] 2023-08-05 23:38
Settings in general do not want to save. Tried in Firefox, Edge and Chrome.

It always just says "Settings stored." but never reboots.

**Comment by revk** [comment] 2023-08-06 01:24
That is weird? Settings are saving in tests here.

Can you check if any browser debug shows any clue. Though if it says settings stored that suggests it is posting Ok.

Does clearing everything out, even WiFi, save? Yes you will have to connect to it as AP to fix that. If settings do save.

I'll recheck the code anyway.

**Comment by revk** [comment] 2023-08-06 06:21
Just to double check - you are actually changing a setting in these cases, yes? It won't reboot if no changes.

I would upgrade to latest code as well if you can.

**Comment by pfak** [comment] 2023-08-06 13:14
I am now on e72ea1c. Every time I make a change to settings it now says "Rebooting" and the settings work. Before it would just say "MQTT Connecting" and not work. **Is the issue if the MQTT username is wrong then settings cant be saved??**

After rebooting for the OTA, the MQTT username is correct from what was supposedly 'saved'. I can confirm it was not working before because I had to create the wrong username for MQTT to be able to control via Home Assistant.

Previously I had tried to change Timezone, MQTT username, MQTT password.

There is one error occasionally, but this does not affect saving/rebooting:

![image](https://github.com/revk/ESP32-Faikin/assets/195072/c6b0dda7-5a3b-45d5-b387-4abd3bdd86e8)

**Comment by revk** [comment] 2023-08-06 13:16
OK, that really is weird - short of some special characters that are not being handled properly, or some weird caching, I am at a loss.

So working now? Apart from referencing the send button? That is odd.

**Comment by pfak** [comment] 2023-08-06 13:19
I can reproduce the issue.

If MQTT is stuck in "Connecting", i.e. username is wrong, then it will not reboot the device. How do I reboot it? :)

**Comment by pfak** [comment] 2023-08-06 13:19
![image](https://github.com/revk/ESP32-Faikin/assets/195072/5b161570-2de0-4c84-bf1f-98618c1e1ade)

**Comment by pfak** [comment] 2023-08-06 13:22
It also does not appear to ever exit the "MQTT Connecting" loop, even when I create the user that I set the settings to.

**Comment by pfak** [comment] 2023-08-06 13:24
It also says "No changes" if I try to change the username.

**Comment by pfak** [comment] 2023-08-06 13:25
Blanking MQTT username, password, host
"Settings stored", stays at that page
No "Rebooting"
Go back to Settings page, MQTT username, password and IP are still there.

**Comment by revk** [comment] 2023-08-06 13:27
"MQTT Connecting" is just the state of the MQTT task, it should probably say MQTT failed if the credentials are wrong, and I can look in to that. It may depend on how your MQTT server responds.

It should, however, not have any impact on either storing settings or rebooting, or allowing you to go back to the settings again and making further changes.

But I'll see if I can reproduce with incorrect MQTT settings - is it the hostname wrong, or just username wrong on a correct hostname?

**Comment by revk** [comment] 2023-08-06 13:27
Ooh, I wonder if that is crashing it somehow, I'll check that now.

**Comment by pfak** [comment] 2023-08-06 13:28
Username is just wrong to repro this problem. 

I changed it from "first-floor-faikin" to "first-floor-faikin2". Now I am in the same situation as when I submitted this ticket, where I can't fix the MQTT settings to make the unit work. I also can't change WiFi, Timezone, etc.

**Comment by pfak** [comment] 2023-08-06 13:29
Even creating an MQTT username "first-floor-faikin2" and it seems stuck :D

**Comment by pfak** [comment] 2023-08-06 13:30
Is there a way to force a reboot of the unit via a GET request?

**Comment by revk** [comment] 2023-08-06 13:32
No there is not - it should not need a reboot. Let me see if I can reproduce this at all.

**Comment by revk** [comment] 2023-08-06 13:37
Every change I make is working, storing settings, and rebooting...

Ideally I could do with a concrete example of specific SSID, password, MQTT hostname, username, password that definitely fails for you, assuming timezone is default. It could be some complicated matter with length of the post or something.

**Comment by revk** [comment] 2023-08-06 13:37
Also, when you say "stuck", I assume you can click on "Home", and then "Settings" again, and get back to the form, regardless?

**Comment by pfak** [comment] 2023-08-06 13:40
> Also, when you say "stuck", I assume you can click on "Home", and then "Settings" again, and get back to the form, regardless?

Correct.

Hostname: `First-Floor-DaikinAC`
SSID: `KIESER-IOT`
Password: `15 character string A-Za-z0-9`
MQTT host: `192.168.3.10`
MQTT username (failing on): `first-floor-daikinac2`
MQTT username (actual): `first-floor-daikinac`
MQTT password: `OyrasHejbutBuv1`
Timezone `PST8PDT,M3.2.0,M11.1.0` 

Originally I could not get the timezone off of BST.

**Comment by pfak** [comment] 2023-08-06 13:42
~5-10 minutes after I create the MQTT username `first-floor-daikinac2` it was able to connect, and then I was able to change the username back to `first-floor-daikinac` and now settings save and reboot again.

**Comment by pfak** [comment] 2023-08-06 13:43
But now ...
![image](https://github.com/revk/ESP32-Faikin/assets/195072/a187fb2c-dd2a-440f-aadb-b44c3bd17cc6)

**Comment by pfak** [comment] 2023-08-06 13:47
Sorry I accidentally typed `first-floor-daikinac` when I meant to put `first-floor-faikin`. This was juts me typing it wrong it is faikin in the settings.

**Comment by revk** [comment] 2023-08-06 13:48
The only clue is the total post length is limited to 200 bytes, but I don't think you could be getting close unless something is % encoding a lot.

I'll just test a change to that in case it is the cause.

**Comment by pfak** [comment] 2023-08-06 13:49
The clue to me is it only fails when MQTT is stuck in connecting state.
As soon as MQTT is not stuck in connecting state, settings save fine.

**Comment by revk** [comment] 2023-08-06 13:51
The MQTT connecting is not a state for the whole system - it is one task in that state. The issue sounds like somehow it is crashing perhaps which would mean the web page does not reload, and settings may not be committed to flash, and so on. I'll see what I can recreate here.

**Comment by revk** [comment] 2023-08-06 13:58
I am testing a failed MQTT connection scenario now.

**Comment by revk** [comment] 2023-08-06 14:10
I may have reproduced it - and not a crash, which is weird in itself!

**Comment by revk** [comment] 2023-08-06 14:14
OK I have found the underlying issue. I'll work on a fix now, and a work around to get you back running. Bear with me.

**Comment by pfak** [comment] 2023-08-06 14:15
im back up and running, but fixing the underlying bug would be fantastic! thank you for your response

**Comment by revk** [comment] 2023-08-06 14:54
OK found it - was MQTT error handling in a subtle way - issuing fix, please do test.

If you are having trouble changing settings of upgrading, stop your MQTT server. It is the connection failing that is constantly aborting the normal reset. Hence you managing to occasionally save, etc.

**Closed by revk** 2023-08-06 14:54 UTC
